FROM amazon/aws-cli
COPY build.sh .

ADD BP-BASE-SHELL-STEPS /opt/buildpiper/shell-functions/

ENV LAUNCHTEMPLATE_ID ""
ENV ASG_NAME ""

ENV SLEEP_DURATION 5s
ENV ACTIVITY_SUB_TASK_CODE INSTANCE_REFERESH
ENV VALIDATION_FAILURE_ACTION WARNING

ENTRYPOINT [ "./build.sh" ]
